# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metaMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import c2s_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metaMessage.proto',
  package='de.velcommuta.denul.network.meta',
  serialized_pb=_b('\n\x11metaMessage.proto\x12 de.velcommuta.denul.network.meta\x1a\tc2s.proto\"\x8e\x03\n\x07Wrapper\x12\x43\n\x0b\x43lientHello\x18\x01 \x01(\x0b\x32,.de.velcommuta.denul.network.c2s.ClientHelloH\x00\x12\x43\n\x0bServerHello\x18\x02 \x01(\x0b\x32,.de.velcommuta.denul.network.c2s.ServerHelloH\x00\x12\x37\n\x05Store\x18\x03 \x01(\x0b\x32&.de.velcommuta.denul.network.c2s.StoreH\x00\x12\x41\n\nStoreReply\x18\x04 \x01(\x0b\x32+.de.velcommuta.denul.network.c2s.StoreReplyH\x00\x12\x33\n\x03Get\x18\x05 \x01(\x0b\x32$.de.velcommuta.denul.network.c2s.GetH\x00\x12=\n\x08GetReply\x18\x06 \x01(\x0b\x32).de.velcommuta.denul.network.c2s.GetReplyH\x00\x42\t\n\x07message')
  ,
  dependencies=[c2s_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WRAPPER = _descriptor.Descriptor(
  name='Wrapper',
  full_name='de.velcommuta.denul.network.meta.Wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ClientHello', full_name='de.velcommuta.denul.network.meta.Wrapper.ClientHello', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ServerHello', full_name='de.velcommuta.denul.network.meta.Wrapper.ServerHello', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Store', full_name='de.velcommuta.denul.network.meta.Wrapper.Store', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StoreReply', full_name='de.velcommuta.denul.network.meta.Wrapper.StoreReply', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Get', full_name='de.velcommuta.denul.network.meta.Wrapper.Get', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GetReply', full_name='de.velcommuta.denul.network.meta.Wrapper.GetReply', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='de.velcommuta.denul.network.meta.Wrapper.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=67,
  serialized_end=465,
)

_WRAPPER.fields_by_name['ClientHello'].message_type = c2s_pb2._CLIENTHELLO
_WRAPPER.fields_by_name['ServerHello'].message_type = c2s_pb2._SERVERHELLO
_WRAPPER.fields_by_name['Store'].message_type = c2s_pb2._STORE
_WRAPPER.fields_by_name['StoreReply'].message_type = c2s_pb2._STOREREPLY
_WRAPPER.fields_by_name['Get'].message_type = c2s_pb2._GET
_WRAPPER.fields_by_name['GetReply'].message_type = c2s_pb2._GETREPLY
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['ClientHello'])
_WRAPPER.fields_by_name['ClientHello'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['ServerHello'])
_WRAPPER.fields_by_name['ServerHello'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Store'])
_WRAPPER.fields_by_name['Store'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['StoreReply'])
_WRAPPER.fields_by_name['StoreReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Get'])
_WRAPPER.fields_by_name['Get'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['GetReply'])
_WRAPPER.fields_by_name['GetReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['Wrapper'] = _WRAPPER

Wrapper = _reflection.GeneratedProtocolMessageType('Wrapper', (_message.Message,), dict(
  DESCRIPTOR = _WRAPPER,
  __module__ = 'metaMessage_pb2'
  # @@protoc_insertion_point(class_scope:de.velcommuta.denul.network.meta.Wrapper)
  ))
_sym_db.RegisterMessage(Wrapper)


# @@protoc_insertion_point(module_scope)
