# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metaMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import c2s_pb2
import studyMessage_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metaMessage.proto',
  package='de.velcommuta.denul.networking.protobuf.meta',
  serialized_pb=_b('\n\x11metaMessage.proto\x12,de.velcommuta.denul.networking.protobuf.meta\x1a\tc2s.proto\x1a\x12studyMessage.proto\"\xe0\x07\n\x07Wrapper\x12O\n\x0b\x43lientHello\x18\x01 \x01(\x0b\x32\x38.de.velcommuta.denul.networking.protobuf.c2s.ClientHelloH\x00\x12O\n\x0bServerHello\x18\x02 \x01(\x0b\x32\x38.de.velcommuta.denul.networking.protobuf.c2s.ServerHelloH\x00\x12\x43\n\x05Store\x18\x03 \x01(\x0b\x32\x32.de.velcommuta.denul.networking.protobuf.c2s.StoreH\x00\x12M\n\nStoreReply\x18\x04 \x01(\x0b\x32\x37.de.velcommuta.denul.networking.protobuf.c2s.StoreReplyH\x00\x12?\n\x03Get\x18\x05 \x01(\x0b\x32\x30.de.velcommuta.denul.networking.protobuf.c2s.GetH\x00\x12I\n\x08GetReply\x18\x06 \x01(\x0b\x32\x35.de.velcommuta.denul.networking.protobuf.c2s.GetReplyH\x00\x12\x45\n\x06\x44\x65lete\x18\x07 \x01(\x0b\x32\x33.de.velcommuta.denul.networking.protobuf.c2s.DeleteH\x00\x12O\n\x0b\x44\x65leteReply\x18\x08 \x01(\x0b\x32\x38.de.velcommuta.denul.networking.protobuf.c2s.DeleteReplyH\x00\x12S\n\x0cStudyWrapper\x18\t \x01(\x0b\x32;.de.velcommuta.denul.networking.protobuf.study.StudyWrapperH\x00\x12[\n\x10StudyCreateReply\x18\n \x01(\x0b\x32?.de.velcommuta.denul.networking.protobuf.study.StudyCreateReplyH\x00\x12\x61\n\x13StudyJoinQueryReply\x18\r \x01(\x0b\x32\x42.de.velcommuta.denul.networking.protobuf.study.StudyJoinQueryReplyH\x00\x12[\n\x10StudyDeleteReply\x18\x0e \x01(\x0b\x32?.de.velcommuta.denul.networking.protobuf.study.StudyDeleteReplyH\x00\x42\t\n\x07message')
  ,
  dependencies=[c2s_pb2.DESCRIPTOR,studyMessage_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WRAPPER = _descriptor.Descriptor(
  name='Wrapper',
  full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ClientHello', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.ClientHello', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ServerHello', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.ServerHello', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Store', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.Store', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StoreReply', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.StoreReply', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Get', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.Get', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GetReply', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.GetReply', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Delete', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.Delete', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeleteReply', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.DeleteReply', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StudyWrapper', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.StudyWrapper', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StudyCreateReply', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.StudyCreateReply', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StudyJoinQueryReply', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.StudyJoinQueryReply', index=10,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StudyDeleteReply', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.StudyDeleteReply', index=11,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='de.velcommuta.denul.networking.protobuf.meta.Wrapper.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=99,
  serialized_end=1091,
)

_WRAPPER.fields_by_name['ClientHello'].message_type = c2s_pb2._CLIENTHELLO
_WRAPPER.fields_by_name['ServerHello'].message_type = c2s_pb2._SERVERHELLO
_WRAPPER.fields_by_name['Store'].message_type = c2s_pb2._STORE
_WRAPPER.fields_by_name['StoreReply'].message_type = c2s_pb2._STOREREPLY
_WRAPPER.fields_by_name['Get'].message_type = c2s_pb2._GET
_WRAPPER.fields_by_name['GetReply'].message_type = c2s_pb2._GETREPLY
_WRAPPER.fields_by_name['Delete'].message_type = c2s_pb2._DELETE
_WRAPPER.fields_by_name['DeleteReply'].message_type = c2s_pb2._DELETEREPLY
_WRAPPER.fields_by_name['StudyWrapper'].message_type = studyMessage_pb2._STUDYWRAPPER
_WRAPPER.fields_by_name['StudyCreateReply'].message_type = studyMessage_pb2._STUDYCREATEREPLY
_WRAPPER.fields_by_name['StudyJoinQueryReply'].message_type = studyMessage_pb2._STUDYJOINQUERYREPLY
_WRAPPER.fields_by_name['StudyDeleteReply'].message_type = studyMessage_pb2._STUDYDELETEREPLY
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['ClientHello'])
_WRAPPER.fields_by_name['ClientHello'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['ServerHello'])
_WRAPPER.fields_by_name['ServerHello'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Store'])
_WRAPPER.fields_by_name['Store'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['StoreReply'])
_WRAPPER.fields_by_name['StoreReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Get'])
_WRAPPER.fields_by_name['Get'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['GetReply'])
_WRAPPER.fields_by_name['GetReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Delete'])
_WRAPPER.fields_by_name['Delete'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['DeleteReply'])
_WRAPPER.fields_by_name['DeleteReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['StudyWrapper'])
_WRAPPER.fields_by_name['StudyWrapper'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['StudyCreateReply'])
_WRAPPER.fields_by_name['StudyCreateReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['StudyJoinQueryReply'])
_WRAPPER.fields_by_name['StudyJoinQueryReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['StudyDeleteReply'])
_WRAPPER.fields_by_name['StudyDeleteReply'].containing_oneof = _WRAPPER.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['Wrapper'] = _WRAPPER

Wrapper = _reflection.GeneratedProtocolMessageType('Wrapper', (_message.Message,), dict(
  DESCRIPTOR = _WRAPPER,
  __module__ = 'metaMessage_pb2'
  # @@protoc_insertion_point(class_scope:de.velcommuta.denul.networking.protobuf.meta.Wrapper)
  ))
_sym_db.RegisterMessage(Wrapper)


# @@protoc_insertion_point(module_scope)
